### ISSUE TITLE
Array of options

### ISSUE THREAD

**Issue by jmervine** [heroku/configerator#4]
I'd like to make `optional` take an Array for configuring multiple options at a time and then allow for a flag which defines them as a collection and creates a sub `?` method. Example:

```
optional [ :aws_secret, :aws_key, :aws_region ], group: :aws

# where
aws?
=> false # if all aren't defined
```

@joshuatobin @reidmix Discuss!

**Comment by jmervine** [comment]
I'm not suck on `group` as the param, but couldn't think of anything better.

**Comment by joshuatobin** [comment]
@jmervine YES! I love this since we do it in a lot of places.

**Comment by reidmix** [comment]
Go forth, I like it. 

I'd say `group` could be the casting method.  Maybe?

```
optional aws: [ :aws_secret, :aws_key, :aws_region ], group
optional :aws_secret, string
optional :aws_key string
...
```

**Comment by jmervine** [comment]
If group were a casting method, it would have to be like array, where it was `group(int)` for example. But that's a good idea for sure!

**Comment by reidmix** [comment]
right... that would be an odd way to go about it... make maybe more since that "group" ends up being like optional/override/required as they are creating the methods, etc. 

Looks like you'll be experimenting.  I'd start out by figuring how you want it to look in config and then go from there (which you are doing)

**Comment by jmervine** [comment]
Addressed with namespaces.
